### ISSUE TITLE
Something's wrong at Plack/Middleware/WebSocket.pm line 57

### ISSUE THREAD

**Issue by cosimo** [motemen/Plack-Middleware-WebSocket#4]
Hi there,

I tried Plack::Middleware::WebSocket for a quick websockets demo, just the echo example, nothing more. However, I can't seem to make this work. I also tried upgrading Plack to the very latest and greatest. This is on Ubuntu 10.04.

I can trace the browser connection up to the inner `read $fh, my $chunk, 8`. For some reason, the `read` function locks up, and returns around 10 seconds later, with `$!` set to `Something's wrong at Plack/Middleware/WebSocket.pm line nnn` where `nnn` is the line where the "read" occurs.

I also tried comparing different websocket modules, but I can't see anything strangely different. It just locks up, and after ~10 seconds the browser is disconnected.

I kept everything equal, and switched to a minimal Mojolicious example, and it works. Also a node.js example works too. I'd prefer using Plack and your middleware if possible, but I'm kind of stuck.

Any idea?

**Comment by qknight** [comment]
use wireshark to get the low level details. since you also got a different websocket implementation, just have a look.

maybe a problem with different protocols since this codebase is from 2010 and we got 2016 now.

**Comment by motemen** [comment]
Thanks, Just updated README, this module is obsolete as it being not up to date.
